### PR TITLE
chore(#180): add list of breaking changes

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

#180 
# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
what do you think, @njuguna-n ? Any thoughts on what to add to this list?

**Comment by njuguna-n** [comment]
This looks good @dianabarsan. This is just for CHT Sync and there will be a separate update to the CHT Pipeline repo as well right? Just want to confirm before approving.

**Comment by dianabarsan** [comment]
It will be separate.

**Review by njuguna-n — APPROVED** [review]
🚀

**Pull request merged**
