### PR TITLE
chore: rename default database in env template

### PR DESCRIPTION
**Pull request by njuguna-n**
# Description

closes medic/cht-sync#167

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by njuguna-n** [comment]
@andrablaj assigning to you for the same reason you stated [here](https://github.com/medic/cht-docs/pull/1630#pullrequestreview-2377999540). Hope that is okay.

**Review by andrablaj — COMMENTED** [review]
Do we also need to update `values.yaml.template` file with the same default value? The values in the two templates don't seem to match (maybe they don't need to, but asking to clarify).

**Comment by njuguna-n** [comment]
The db value in the `values.yaml.template` file is currently blank ensuring someone has to add it and I prefer to keep it that way. I have updated the table name to match the `env.template` file though.

**Review by andrablaj — APPROVED** [review]

**Comment by mrjones-plip** [comment]
love that this change is only in 2 files - it means we truly didn't hard code the values and can just make a quick change \o/

**Pull request merged**
