### PR TITLE
feat: add versioning and releases

### PR DESCRIPTION
**Pull request by njuguna-n**
# Description
Add automatic versioning and releases to CHT Sync

medic/cht-sync#35

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by dianabarsan — CHANGES_REQUESTED** [review]
I think we need to clean up a bit.
What are we even releasing here? Are we publishing to npm? 
If I run `npm publish --dry-run` it ends up publishing everything, including node_modules. Not cool. 

I don't think npm should be the place to publish cht-sync. I think these should be docker images, just like the CHT, not npm packages.

**Comment by njuguna-n** [comment]
There is already a [GHA](https://github.com/medic/cht-sync/blob/86e0b131001998002d0ec506bcf0d06f89244277/.github/workflows/build.yml) that publishes the containers to Docker Hub. This is meant to simply add versions and releases with the zipped source code similar to [CHT Watchdog](https://github.com/medic/cht-watchdog/releases)

**Comment by njuguna-n** [comment]
Hi @dianabarsan I am uncertain what changes need to be made to have this merged. Should I set the [private](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#private) config to avoid publishing to npm?

**Comment by dianabarsan** [comment]
Oh cool. I think we should change how the publishing to docker works so that we include versioning there. so you would map the image tag to the version and not publish to npm at all.

**Pull request merged**
